config/routes.rb
Rails.application.routes.draw do
  resources :attachments do
    get "serve", :on => :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def index
    @attachments = Attachment.all
  end

  def show
    @attachment = Attachment.find(params[:id])
    send_data(@attachment.data,
           type: @attachment.mime_type,
           filename: @attachment.filename)
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.new(attachment_params) do |t|
      if params[:attachment][:data]
        t.data      = params[:attachment][:data].read
        t.filename  = params[:attachment][:data].original_filename
        t.mime_type = params[:attachment][:data].content_type
      end
    end

    if @attachment.save
      redirect_to(attachments_path, :notice => 'attachment was successfully created.')
    else
      render :action => "new"
    end
  end

  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy
    redirect_to(attachments_url)
  end

  def serve
     # @attachment = Attachment.find(params[:id])
     # send_data(@attachment.data, :type => @attachment.mime_type, :filename => "#{@attachment.name}", :disposition => "inline")
   end

   private
   # Use callbacks to share common setup or constraints between actions.
   def set_attachment
     @attachment = Attachment.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def attachment_params
     params.require(:attachment).permit(:name, :data, :filename, :mime_type)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/index.html.haml
%table
  %thead

  %tbody
    - @attachments.each do |att|
      %tr
        %td= att.name
        %td= link_to 'Download', attachment_path(att.id)

app/views/attachments/new.html.haml
= form_for(@attachment, :html => {:multipart => true}) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :data
    = f.file_field :data
  .actions
    = f.submit "Upload"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUpload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>